export const dataForFilters = [
  "Apartment",
  "Condominium",
  "House",
  "Loft",
  "Guesthouse",
  "Hostel",
  "Serviced apartment",
  "Bed and breakfast",
  "Treehouse",
  "Bungalow",
  "Guest suite",
  "Townhouse",
  "Villa",
  "Cabin",
  "Chalet",
  "Farm stay",
  "Boutique hotel",
  "Boat",
  "Cottage",
  "Earth house",
];
